const data = {
  products: [
    {
      _id: "1",
      name: "Mebaz blue kurta",
      category: "Kurtas",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Mebaz",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Jockey Jeans",
      category: "jeans",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Jockey",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Mebaz Anarkali",
      category: "Anarkali",
      image: "/images/p3.jpg",
      price: 150,
      brand: "Mebaz",
      rating: 4.5,
      numReview: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Liva green kurti top",
      category: "Kurtas",
      image: "/images/p4.jpg",
      price: 170,
      brand: "Liva",
      rating: 4.5,
      numReview: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Jockey night dress",
      category: "Night dresss",
      image: "/images/p5.jpg",
      price: 110,
      brand: "Jockey",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Max party dress",
      category: "dresss",
      image: "/images/p6.jpg",
      price: 190,
      brand: "Max",
      rating: 4.5,
      numReview: 15,
      description: "high quality product",
    },
  ],
};

export default data;
